DELETE FROM BOOKING;
ALTER TABLE BOOKING ALTER COLUMN ID RESTART WITH 1;
INSERT INTO BOOKING (
    CHECK_IN_DATE,
    CHECK_OUT_DATE,
    CREDIT_CARD_NUMBER,
    NAME,
    NIGHT_STAYS) VALUES (
    '2025-02-21',
    '2025-04-03',
    '2OamBvPnLU+ztooZVrtHaxM0ruVrjK7F3lLWnPnzBpDjcra7SNIAY5ULsqwh49//',
    'John Doe',
    2);